import type { Metadata } from 'next';
import './globals.css';
import QueryProvider from '@/components/QueryProvider';
import { AppSidebar } from '@/components/SideBar';
import { SidebarProvider } from '@/components/ui/sidebar';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="flex">
                <QueryProvider>
                    <SidebarProvider defaultOpen={true}>
                        <AppSidebar />
                        {children}
                    </SidebarProvider>
                </QueryProvider>
            </body>
        </html>
    );
}
